language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  matrix:
    - PROFILE=non-existant
    - PROFILE=spring5-next

cache:
  directories:
    - $HOME/.m2

sudo: false
install: true
script: "./mvnw clean dependency:list test -Dsort"
